#!/usr/bin/env bash
# The three writes the assistant makes in Problem 3, as MCP tool calls.
cd "$(dirname "$0")/../assistant"
NOW=$(( $(date +%s) * 1000 ))
echo "## write 1: rca annotation on the dashboard"
python3 mcp_call.py create_annotation "{\"dashboardUid\":\"cortex-publishing-tier\",\"time\":$NOW,\"tags\":[\"cortex\",\"rca\",\"component:cortex-publisher-service\",\"assistant\"],\"text\":\"RCA (assistant): publisher-service acknowledges Kafka messages but published_content writes are rejected (chaos db-write-fail, config change at $(date -u +%H:%M) UTC). Symptom: approved articles 404 on the site while lag is 0 and dashboards are green. Evidence: publisher_publish_failures_total{reason=db_write} rising, Loki publish_failed lines, Tempo spans with status=error. Fix: revert the config; move the DB write before the offset commit or route failures to a dead-letter topic.\"}" 600
echo; echo "## write 2: alert rule PublishedContentGap"
if python3 mcp_call.py alerting_manage_rules '{"operation":"list","search_rule_name":"PublishedContentGap","limit_alerts":0}' 2000 | grep -q '"title":"PublishedContentGap"'; then echo "already exists (skipping create)"; else
python3 mcp_call.py alerting_manage_rules '{"operation":"create","org_id":1,"folder_uid":"efyjo97jj1o8wf","rule_group":"cortex-publishing-tier","title":"PublishedContentGap","condition":"C","for":"2m","no_data_state":"OK","exec_err_state":"Error","labels":{"severity":"critical","tier":"publishing","team":"content-platform","created_by":"assistant"},"annotations":{"summary":"Content is being consumed from Kafka but not published: {{ $value }} failures/s (reason=db_write means Postgres rejected the write; media means media-service is down). Approved articles will 404 on the site even though lag is 0.","runbook_url":"https://github.com/sathpal/grafana-assistant-demo/blob/main/grafana/runbook.md","dashboard_url":"https://techstronautk8s.grafana.net/d/cortex-publishing-tier"},"data":[{"refId":"A","datasourceUid":"grafanacloud-prom","relativeTimeRange":{"from":600,"to":0},"model":{"refId":"A","expr":"sum(rate(publisher_publish_failures_total[5m]))","instant":true,"range":false}},{"refId":"C","datasourceUid":"__expr__","model":{"refId":"C","type":"threshold","expression":"A","conditions":[{"evaluator":{"type":"gt","params":[0]}}]}}]}' 800
fi
echo; echo "## write 3: dashboard panel"
if python3 mcp_call.py grafana_api_request '{"method":"GET","endpoint":"/api/dashboards/uid/cortex-publishing-tier","jq":"[.dashboard.panels[] | select(.title != null and (.title|startswith(\"Consumed vs published\"))) | .id] | length"}' 200 | grep -qE '"data":[1-9]'; then echo "panel already on the dashboard (skipping)"; else
python3 mcp_call.py update_dashboard '{"uid":"cortex-publishing-tier","message":"assistant: add consumed-vs-published gap panel (Problem 3)","operations":[{"op":"add","path":"$.panels/-","value":{"type":"timeseries","title":"Consumed vs published (gap = silent failures)","description":"Added by the OSS assistant during Problem 3. Consumed = Kafka offsets advancing; published = rows that reached Postgres. A gap means the consumer acknowledged messages it could not persist.","datasource":{"type":"prometheus","uid":"grafanacloud-prom"},"gridPos":{"x":0,"y":3,"w":24,"h":7},"fieldConfig":{"defaults":{"unit":"short","custom":{"lineWidth":2,"fillOpacity":15}},"overrides":[{"matcher":{"id":"byName","options":"failed (silent)"},"properties":[{"id":"color","value":{"mode":"fixed","fixedColor":"red"}},{"id":"custom.fillOpacity","value":60}]}]},"options":{"legend":{"displayMode":"list","placement":"bottom"},"tooltip":{"mode":"multi"}},"targets":[{"refId":"A","datasource":{"type":"prometheus","uid":"grafanacloud-prom"},"expr":"sum(rate(publisher_content_published_total[2m])) * 60","legendFormat":"published / min"},{"refId":"B","datasource":{"type":"prometheus","uid":"grafanacloud-prom"},"expr":"sum(rate(publisher_publish_failures_total[2m])) * 60","legendFormat":"failed (silent)"},{"refId":"C","datasource":{"type":"prometheus","uid":"grafanacloud-prom"},"expr":"sum(rate(kafka_consumergroup_current_offset{consumergroup=\"publisher-service\",topic=~\"cortex.content.*\"}[2m])) * 60","legendFormat":"consumed / min (Kafka offsets)"}]}}]}' 800
fi
echo; echo "## deeplink"; python3 mcp_call.py generate_deeplink '{"resourceType":"dashboard","dashboardUid":"cortex-publishing-tier","timeRange":{"from":"now-30m","to":"now"}}' 300
